export { default as Home } from "./Home/Home";
export { default as Products } from "./Products/Products";
export { default as ProductList } from "./ProductList/ProductList";
export { default as ProductPage } from "./ProductPage/ProductPage";
export { default as Contact } from "./Contact/Contact";
export { default as Admin } from "./Admin/Admin";
export { default as AdminPanel } from "./AdminPanel/AdminPanel";
export { default as Login } from "./Login/Login";
export { default as Error } from "./Error/Error";
